name: 'Meowdding Mods'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  pnpm:
    name: Run fetcher
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Script
        run: |
          node .github/scripts/meowdding_mods_fetcher.mjs

      - name: Commit and push
        continue-on-error: true
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update Meowdding Mods"
          git push
